# config/keywords.py

RAW_KEYWORDS = [
   "ADP",
   "Shutdown",
   "Shutdowns",
   "Shut Down",
   "Shuts Down",
   "Expectation",
   "Expectations",
   "Tariff Inflation",
   "Tariffs Inflation",
   "Tariff Inflations",
   "Credit",
   "Credits",
   "Projection",
   "Projections",
   "Median",
   "Medians",
   "Good Afternoon",
   "Restrictive",
   "Balance of Risk",
   "Balance of Risks",
   "Balance Sheet",
   "Balance Sheets",
   "Beige Book",
   "AI",
   "Artificial Intelligence",
   "Probabilities",
   "Probability",
   "Goods inflation",
   "Good inflation",
   "Layoffs",
   "Layoff",
   "Volatility",
   "Unchanged",
   "Recession",
   "Recessions",
   "Pardon",
   "Pardons",
   "QT",
   "Quantitative Tightening",
   "QE",
   "Quantitative Easing",
   "Trump",
   "Trumps",
   "Trump's",
   "Anchors",
   "Anchor",
   "Soft Landing",
   "Soft Landings",
   "Consumer Confidence",
   "Dot Plot",
   "Dot Plots",
   "Gas",
   "Gases",
   "Gasoline",
   "Natural Gas",
   "Gold",
   "Pandemic",
   "Bitcoin",
   "Tax",
   "Taxes",
   "Egg",
   "Eggs",
   "Yield Curve",
   "Uncertainty",
   "Uncertainties",
   "Trade War",
   "Trade Wars",
   "National Debt",
   "National Debts",
   "Softening",
   "Dissent",
   "Dissents",
   "Stagflation"
]

CANONICAL_KEYWORDS = [
   "ADP",
   "shutdown",
   "shut down",
   "expectation",
   "tariff inflation",
   "credit",
   "projection",
   "median",
   "good afternoon",
   "restrictive",
   "balance of risk",
   "balance sheet",
   "beige book",
   "AI",
   "artificial intelligence",
   "probability",
   "goods inflation",
   "layoff",
   "volatility",
   "unchanged",
   "recession",
   "pardon",
   "QT",
   "quantitative tightening",
   "QE",
   "quantitative easing",
   "trump",
   "anchor",
   "soft landing",
   "consumer confidence",
   "dot plot",
   "gas",
   "gasoline",
   "natural gas",
   "gold",
   "pandemic",
   "bitcoin",
   "tax",
   "egg",
   "yield curve",
   "uncertainty",
   "trade war",
   "national debt",
   "softening",
   "dissent",
   "stagflation"
]

SYNONYM_MAP = {
   "ADP": ["ADP"],
   "shutdown": ["Shutdown", "Shutdowns", "Shut down", "Shuts Down"],
   "expectation": ["Expectation", "Expectations"],
   "tariff inflation": ["Tariff Inflation", "Tariffs Inflation", "Tariff Inflations"],
   "credit": ["Credit", "Credits"],
   "projection": ["Projection", "Projections"],
   "median": ["Median", "Medians"],
   "good afternoon": ["Good Afternoon"],
   "restrictive": ["Restrictive"],
   "balance of risk": ["Balance of Risk", "Balance of Risks"],
   "balance sheet": ["Balance Sheet", "Balance Sheets"],
   "beige book": ["Beige Book"],
   "AI": ["AI", "Artificial Intelligence"],
   "probability": ["Probability"],
   "goods inflation": ["Goods inflation", "Good inflation"],
   "layoff": ["Layoff", "Layoffs"],
   "volatility": ["Volatility"],
   "unchanged": ["Unchanged"],
   "recession": ["Recession", "Recessions"],
   "pardon": ["Pardon", "Pardons"],
   "QT": ["QT", "Quantitative Tightening"],
   "QE": ["QE", "Quantitative Easing"],
   "trump": ["Trump", "Trumps", "Trump's"],
   "anchor": ["Anchor", "Anchors"],
   "soft landing": ["Soft Landing", "Soft Landings"],
   "consumer confidence": ["Consumer Confidence"],
   "dot plot": ["Dot Plot", "Dot Plots"],
   "gas": ["Gas", "Gases", "Gasoline", "Natural Gas"],
   "gold": ["Gold"],
   "pandemic": ["Pandemic"],
   "bitcoin": ["Bitcoin"],
   "tax": ["Tax", "Taxes"],
   "egg": ["Egg", "Eggs"],
   "yield curve": ["Yield Curve"],
   "uncertainty": ["Uncertainty", "Uncertainties"],
   "trade war": ["Trade War", "Trade Wars"],
   "national debt": ["National Debt", "National Debts"],
   "softening": ["Softening"],
   "dissent": ["Dissent", "Dissents"],
   "stagflation": ["Stagflation"]
}

TRENDS_SYNONYMS = {
   "ADP": ["ADP"],
   "shutdown": ["Shutdown", "Shutdowns", "Shut down", "Shuts Down"],
   "expectation": ["Expectation", "Expectations"],
   "tariff inflation": ["Tariff Inflation", "Tariffs Inflation", "Tariff Inflations"],
   "credit": ["Credit", "Credits"],
   "projection": ["Projection", "Projections"],
   "median": ["Median", "Medians"],
   "good afternoon": ["Good Afternoon"],
   "restrictive": ["Restrictive"],
   "balance of risk": ["Balance of Risk", "Balance of Risks"],
   "balance sheet": ["Balance Sheet", "Balance Sheets"],
   "beige book": ["Beige Book"],
   "AI": ["AI", "Artificial Intelligence"],
   "probability": ["Probability"],
   "goods inflation": ["Goods inflation", "Good inflation"],
   "layoff": ["Layoff", "Layoffs"],
   "volatility": ["Volatility"],
   "unchanged": ["Unchanged"],
   "recession": ["Recession", "Recessions"],
   "pardon": ["Pardon", "Pardons"],
   "QT": ["QT", "Quantitative Tightening"],
   "QE": ["QE", "Quantitative Easing"],
   "trump": ["Trump", "Trumps", "Trump's"],
   "anchor": ["Anchor", "Anchors"],
   "soft landing": ["Soft Landing", "Soft Landings"],
   "consumer confidence": ["Consumer Confidence"],
   "dot plot": ["Dot Plot", "Dot Plots"],
   "gas": ["Gas", "Gases", "Gasoline", "Natural Gas"],
   "gold": ["Gold"],
   "pandemic": ["Pandemic"],
   "bitcoin": ["Bitcoin"],
   "tax": ["Tax", "Taxes"],
   "egg": ["Egg", "Eggs"],
   "yield curve": ["Yield Curve"],
   "uncertainty": ["Uncertainty", "Uncertainties"],
   "trade war": ["Trade War", "Trade Wars"],
   "national debt": ["National Debt", "National Debts"],
   "softening": ["Softening"],
   "dissent": ["Dissent", "Dissents"],
   "stagflation": ["Stagflation"]
}

# Lower case normalization
RAW_KEYWORDS = [kw.lower() for kw in RAW_KEYWORDS]

CANONICAL_KEYWORDS = [kw.lower() for kw in CANONICAL_KEYWORDS]

SYNONYM_MAP = {
    k.lower(): [v.lower() for v in vals]
    for k, vals in SYNONYM_MAP.items()
}

TRENDS_SYNONYMS = {
    k.lower(): [v.lower() for v in vals]
    for k, vals in TRENDS_SYNONYMS.items()
}